//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suntvaccinat.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suntvaccinat.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnLabel {
            get {
                return ResourceManager.GetString("CancelBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m vaccinated.
        /// </summary>
        public static string ClientBtnLabel {
            get {
                return ResourceManager.GetString("ClientBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the certificate type.
        /// </summary>
        public static string ClientCertificateSelectionLabel {
            get {
                return ResourceManager.GetString("ClientCertificateSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Green Pass.
        /// </summary>
        public static string ClientGPMethodLabel {
            get {
                return ResourceManager.GetString("ClientGPMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the INSP certificate.
        /// </summary>
        public static string ClientINSPMethodLabel {
            get {
                return ResourceManager.GetString("ClientINSPMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as .
        /// </summary>
        public static string ContinueMessage {
            get {
                return ResourceManager.GetString("ContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from INSP site.
        /// </summary>
        public static string DownloadINSPBtnLabel {
            get {
                return ResourceManager.GetString("DownloadINSPBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventsPageLabel {
            get {
                return ResourceManager.GetString("EventsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FemaleGenderLabel {
            get {
                return ResourceManager.GetString("FemaleGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add a participant to the event.
        /// </summary>
        public static string ForAddingToEventMsg {
            get {
                return ResourceManager.GetString("ForAddingToEventMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Pass.
        /// </summary>
        public static string GreenPassLabel {
            get {
                return ResourceManager.GetString("GreenPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add information.
        /// </summary>
        public static string InformationPageTitle {
            get {
                return ResourceManager.GetString("InformationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSP.
        /// </summary>
        public static string INSPLabel {
            get {
                return ResourceManager.GetString("INSPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MaleGenderLabel {
            get {
                return ResourceManager.GetString("MaleGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextBtnLabel {
            get {
                return ResourceManager.GetString("NextBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        public static string OrganizerBtnLabel {
            get {
                return ResourceManager.GetString("OrganizerBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OrLabel {
            get {
                return ResourceManager.GetString("OrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or on .
        /// </summary>
        public static string OrOnMsg {
            get {
                return ResourceManager.GetString("OrOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from Device.
        /// </summary>
        public static string PickINSPBtnLabel {
            get {
                return ResourceManager.GetString("PickINSPBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code here.
        /// </summary>
        public static string PlaceholderGP {
            get {
                return ResourceManager.GetString("PlaceholderGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press on .
        /// </summary>
        public static string PressOnMsg {
            get {
                return ResourceManager.GetString("PressOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back,.
        /// </summary>
        public static string ProfilePageMsgLabel {
            get {
                return ResourceManager.GetString("ProfilePageMsgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Green Pass.
        /// </summary>
        public static string RemoveGreenPassLabel {
            get {
                return ResourceManager.GetString("RemoveGreenPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove INSP .
        /// </summary>
        public static string RemoveINSPLabel {
            get {
                return ResourceManager.GetString("RemoveINSPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        public static string RemoveUserLabel {
            get {
                return ResourceManager.GetString("RemoveUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        public static string ScanGPBtnLabel {
            get {
                return ResourceManager.GetString("ScanGPBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name (ex: Ilie-Cristian, Vasile).
        /// </summary>
        public static string SecondNameLabel {
            get {
                return ResourceManager.GetString("SecondNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powered by suntvaccinat.ro.
        /// </summary>
        public static string SloganLabel {
            get {
                return ResourceManager.GetString("SloganLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new event.
        /// </summary>
        public static string ToAddNewEventMsg {
            get {
                return ResourceManager.GetString("ToAddNewEventMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close the event.
        /// </summary>
        public static string ToCloseEventMsg {
            get {
                return ResourceManager.GetString("ToCloseEventMsg", resourceCulture);
            }
        }
    }
}
